after_script:
  - docker images

before_script:
  - cd "$VERSION"
  - IMAGE="sparks-core:${VERSION/\//-}"

env:
  - VERSION=0.12
  - VERSION=0.12/alpine

language: bash

script:
  - docker build -t "$IMAGE" .
  - docker run "$IMAGE" --version | grep "Sparks Core"

services: docker
